version: "3.9"
services:
  template:
    container_name: template
    image: go-app-template
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - FILE_NAME
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro